[package]
name = "subxt-revive"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.98"
hex = "0.4.3"
subxt = "0.42.1"
subxt-signer = "0.42.1"
tokio = { version = "1.45.1", features = ["full"] }
